### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ldexterldesign** [nh2/sublime-text-move-tabs#7]
Hey,

Does this package still work (i.e. ctrl + tab, left to right like https://www.google.com/intl/en/chrome/browser/ ), if so where's the documentation to get it setup?

I just installed it, but it's not working out of the box??

Yours hopefully,

**Comment by nh2** [comment]
Yes, works for me. What OS are you on, and do you use Sublime 2 or 3?

**Comment by ldexterldesign** [comment]
Hey,

Thanks for reply

OS X 10.9.1 (Mavericks) and latest Sublime (so v3)

Yours hopefully,

**Comment by nh2** [comment]
I think it was simply because there were no Mac keybindings (I don't have a Mac to test it with).

I just merged https://github.com/nh2/sublime-text-move-tabs/pull/6 - can you give it a try and tell me if that works?

**Comment by ldexterldesign** [comment]
Hey,

Sure, can I install this update through https://sublime.wbond.net/packages/Package%20Control else could you provide some installation guidance?

Kind thanks,

**Comment by ldexterldesign** [comment]
_Bump_

Is this compatible with http://www.sublimetext.com/3 or am I missing some documentation - can't get it to work?

Cheers,

**Comment by nh2** [comment]
Yes, it is available via Pckage Control for Sublime Text 2.

For Sublime Text 3, you can get another package via Package Control: https://sublime.wbond.net/packages/MoveTab.

**Comment by ldexterldesign** [comment]
Hey,

Thanks for coming back to me

That _is_ the package I'm using, but still not working how I'd like. In Chrome you can tab along the tabs (left to right) using Crtl + Tab. After installing this package it's not the case?

Are there some settings/config I'm missing?

Cheers,

**Comment by nh2** [comment]
That is because in sublime ctrl-tab already has a binding: it goes back to the last tab. The move tab plug-ins only implement ctrl-pageup/down for going to the previous / next tab.

**Comment by ldexterldesign** [comment]
Hey,

This seems to have done the trick:
![screen shot 2014-04-13 at 13 10 56](https://cloud.githubusercontent.com/assets/1715809/2689416/b5725d00-c304-11e3-9b78-d5a188537398.png)

Cheers,
